// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostCodeLookupAPI.Helpers;

namespace PostCodeLookupAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200818024235_IntialMigrion")]
    partial class IntialMigrion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PostCodeLookupAPI.Entities.PostcodeLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeliveryInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PostCodeLookup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryInfo = "Delivery from Warehouse",
                            PostCode = "TN9"
                        },
                        new
                        {
                            Id = 2,
                            DeliveryInfo = "No Deliveries",
                            PostCode = "TN9 1AP"
                        },
                        new
                        {
                            Id = 3,
                            DeliveryInfo = "Delivery from Warehouse",
                            PostCode = "TN8"
                        },
                        new
                        {
                            Id = 4,
                            DeliveryInfo = "Delivery from Warehouse",
                            PostCode = "TN11"
                        },
                        new
                        {
                            Id = 5,
                            DeliveryInfo = "Van Delivery, Collect from Tunbridge Wells",
                            PostCode = "TN1"
                        },
                        new
                        {
                            Id = 6,
                            DeliveryInfo = "Van Delivery, Collect from Tunbridge Wells",
                            PostCode = "TN2"
                        },
                        new
                        {
                            Id = 7,
                            DeliveryInfo = "Van Delivery",
                            PostCode = "TN10"
                        },
                        new
                        {
                            Id = 8,
                            DeliveryInfo = "Delivery from Sevenoaks, Collect from Sevenoaks",
                            PostCode = "TN13"
                        },
                        new
                        {
                            Id = 9,
                            DeliveryInfo = "Delivery from Sevenoaks, Collect from Sevenoaks",
                            PostCode = "TN14"
                        },
                        new
                        {
                            Id = 10,
                            DeliveryInfo = "Collect from Sevenoaks",
                            PostCode = "TN15"
                        },
                        new
                        {
                            Id = 11,
                            DeliveryInfo = "No Deliveries",
                            PostCode = "ME"
                        },
                        new
                        {
                            Id = 12,
                            DeliveryInfo = "Collect from Kitchen",
                            PostCode = "ME10"
                        },
                        new
                        {
                            Id = 13,
                            DeliveryInfo = "Collect from Kitchen, Delivery from Sittingbourne",
                            PostCode = "ME10 3"
                        },
                        new
                        {
                            Id = 14,
                            DeliveryInfo = "No Deliveries",
                            PostCode = "IV"
                        },
                        new
                        {
                            Id = 15,
                            DeliveryInfo = "Delivery by Courier",
                            PostCode = ""
                        });
                });

            modelBuilder.Entity("PostCodeLookupAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
